-- Włączenie rozszerzenia PostGIS dla obsługi lokalizacji (geography)
CREATE EXTENSION IF NOT EXISTS postgis;

-- --- CZYSZCZENIE STARYCH TYPÓW (OPCJONALNE PRZY RESTARCIE) ---
DROP TYPE IF EXISTS listing_status CASCADE;
DROP TYPE IF EXISTS listing_type CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS user_status CASCADE;

-- --- TWORZENIE TABEL ---

-- Tabela: Users
CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR DEFAULT 'INACTIVE' NOT NULL,
    role VARCHAR DEFAULT 'USER' NOT NULL,
    review_count INTEGER NOT NULL DEFAULT 0,
    total_grade_sum BIGINT NOT NULL DEFAULT 0
    );

-- Tabela: Items
CREATE TABLE IF NOT EXISTS items (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR NOT NULL,
                                     founder_id INTEGER,
                                     owner_id INTEGER
);

-- Tabela: Listings
CREATE TABLE IF NOT EXISTS listings (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        status VARCHAR DEFAULT 'ACTIVE' NOT NULL,
                                        listing_type VARCHAR DEFAULT 'FOUND' NOT NULL,
                                        item_id INTEGER NOT NULL UNIQUE,
                                        author_id INTEGER NOT NULL,
                                        location geography(Point, 4326) NOT NULL,
    description TEXT NOT NULL
    );

-- Tabela: Images
CREATE TABLE IF NOT EXISTS images (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      item_id INTEGER NOT NULL,
                                      image_url VARCHAR(100)
    );

-- Tabela: Message Rooms
CREATE TABLE IF NOT EXISTS message_rooms (
                                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             listing_id INTEGER NOT NULL,
                                             listing_owner_id INTEGER NOT NULL,
                                             item_claimant_id INTEGER NOT NULL
);

-- Tabela: Messages
CREATE TABLE IF NOT EXISTS messages (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        message_room_id INTEGER NOT NULL,
                                        content TEXT NOT NULL,
                                        timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                        is_read BOOLEAN DEFAULT FALSE NOT NULL,
                                        sender_id INTEGER NOT NULL
);

-- Tabela: Payments
CREATE TABLE IF NOT EXISTS payments (
                                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        sender_id INTEGER NOT NULL,
                                        receiver_id INTEGER NOT NULL,
                                        amount NUMERIC(10, 2) NOT NULL,
    listing_id INTEGER NOT NULL,
    status VARCHAR DEFAULT 'PENDING' NOT NULL,
    provider VARCHAR(50) NOT NULL,
    currency VARCHAR(3) DEFAULT 'PLN' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    paid_at TIMESTAMP WITHOUT TIME ZONE
    );

-- Tabela: Reviews (ZAKTUALIZOWANA)
CREATE TABLE IF NOT EXISTS reviews (
                                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       founder_id INTEGER NOT NULL,
                                       reviewer_id INTEGER NOT NULL,
                                       item_id INTEGER NOT NULL,  -- Nowa kolumna
                                       grade INTEGER CHECK (grade >= 1 AND grade <= 5),
    -- Zabezpieczenie: Jeden recenzent może wystawić tylko jedną opinię do jednego przedmiotu
    CONSTRAINT uq_reviews_reviewer_item UNIQUE (reviewer_id, item_id)
    );

-- --- KLUCZE OBCE (FOREIGN KEYS) ---

-- Relacje dla Items
ALTER TABLE items
    ADD CONSTRAINT fk_items_founder FOREIGN KEY (founder_id) REFERENCES users (id),
    ADD CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES users (id);

-- Relacje dla Listings
ALTER TABLE listings
    ADD CONSTRAINT fk_listings_author FOREIGN KEY (author_id) REFERENCES users (id),
    ADD CONSTRAINT fk_listings_item FOREIGN KEY (item_id) REFERENCES items (id);

-- Relacje dla Images
ALTER TABLE images
    ADD CONSTRAINT fk_images_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE;

-- Relacje dla Message Rooms
ALTER TABLE message_rooms
    ADD CONSTRAINT fk_rooms_listing FOREIGN KEY (listing_id) REFERENCES listings (id),
    ADD CONSTRAINT fk_rooms_owner FOREIGN KEY (listing_owner_id) REFERENCES users (id),
    ADD CONSTRAINT fk_rooms_claimant FOREIGN KEY (item_claimant_id) REFERENCES users (id);

-- Relacje dla Messages
ALTER TABLE messages
    ADD CONSTRAINT fk_messages_room FOREIGN KEY (message_room_id) REFERENCES message_rooms (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id);

-- Relacje dla Payments
ALTER TABLE payments
    ADD CONSTRAINT fk_payments_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    ADD CONSTRAINT fk_payments_receiver FOREIGN KEY (receiver_id) REFERENCES users (id),
    ADD CONSTRAINT fk_payments_listing FOREIGN KEY (listing_id) REFERENCES listings (id);

-- Relacje dla Reviews (ZAKTUALIZOWANA)
ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_founder FOREIGN KEY (founder_id) REFERENCES users (id),
    ADD CONSTRAINT fk_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (id),
    ADD CONSTRAINT fk_reviews_item FOREIGN KEY (item_id) REFERENCES items (id); -- Nowy klucz obcy